#! /bin/sh

wal -R &
sxhkd &
polybar -c ${HOME}/.config/polybar/config -r laptop &
xrandr --output eDP1 --mode 1920x1080 &
dunst -config ${HOME}/.config/dunst/dunstrc &
compton --respect-prop-shadow --config ${HOME}/.config/compton/compton.conf &
xfsettingsd &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
pcloud &


# source the colors.
. "${HOME}/.cache/wal/colors.sh"
wal -o ~/.config/wal/done.sh
